# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"e\n\x0fGenerateRequest\x12\x16\n\x0e\x63ontext_tokens\x18\x01 \x03(\x05\x12\x16\n\x0emax_new_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_p\x18\x04 \x01(\x02\"@\n\tCandidate\x12\x10\n\x08token_id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\"i\n\rGenerateEvent\x12\x10\n\x08token_id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12(\n\ncandidates\x18\x03 \x03(\x0b\x32\x14.inference.Candidate\x12\x0e\n\x06is_eos\x18\x04 \x01(\x08\x32O\n\tInference\x12\x42\n\x08Generate\x12\x1a.inference.GenerateRequest\x1a\x18.inference.GenerateEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=30
  _globals['_GENERATEREQUEST']._serialized_end=131
  _globals['_CANDIDATE']._serialized_start=133
  _globals['_CANDIDATE']._serialized_end=197
  _globals['_GENERATEEVENT']._serialized_start=199
  _globals['_GENERATEEVENT']._serialized_end=304
  _globals['_INFERENCE']._serialized_start=306
  _globals['_INFERENCE']._serialized_end=385
# @@protoc_insertion_point(module_scope)
